[package]
name = "socket_perf"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
clap = { version = "4.5.48", features = ["derive", "env"]}
log = "0.4.28"
env_logger = "0.11.8"
